// Type: the three families, the scale new work draws from, and every role the site and the system parts set,
// each with its steps per breakpoint. Leading "1.5" with no class means the line height is inherited from the
// page. A system part's role mirrors the class string on its source line, as button-label does.
import { tk, type Token, type TypeRole } from "./token-types";

const W = "components/website/";
const DS = "components/design-system/";

export const FAMILIES: readonly Token[] = [
  tk("font-display", "var(--font-outfit), ui-sans-serif, system-ui, sans-serif", "Outfit 400, 500, 600",
    "Headlines, names, numbers, the wordmark", "Reading text", "app/layout.tsx:11", { utility: "font-display" }),
  tk("font-sans", "var(--font-inter), ui-sans-serif, system-ui, sans-serif", "Inter 400, 500, 600",
    "Body, labels, controls", "Display lines", "app/layout.tsx:5", { utility: "font-sans" }),
  tk("font-mono", "var(--font-jbmono), ui-monospace, SFMono-Regular, Menlo, monospace", "JetBrains Mono 400, 500",
    "Machine text: the terminal, card meta and code at 400, badges at 500", "Prose", "app/layout.tsx:18",
    { utility: "font-[family-name:var(--font-jbmono)]" }),
];

const STEPS = [11, 12, 13, 14, 15, 16, 18, 20, 22, 24, 26, 28, 30, 34, 36, 44, 56] as const;
const USES: Record<number, string> = {
  11: "eyebrow caps, card meta, code tags", 12: "micro labels, the copy line's pills",
  13: "captions, tabs, chips, small controls",
  14: "body S, controls, the container lede", 15: "body L, nav, the CTA label",
  16: "body L from md, FAQ question, comparison lines on phones",
  18: "player body, FAQ question from md, comparison lines from md", 20: "card titles, menu rows", 22: "card names",
  24: "the wordmark", 26: "scroll line, comparison names on phones", 28: "the carousel title", 30: "section h2, stats",
  34: "hero headline, the vs word and comparison names from md", 36: "the carousel title from md",
  44: "section h2 and scroll line from md", 56: "hero and player headline from md",
};

/** The size steps new work may use. Off-scale site sizes stay with their roles: 10, 11.5, 12.5, 13.5 and
 *  16.5, the vs word's 27 on a phone, the full hero's ladder (42 to 88) and the clamped closing and footer
 *  words. */
export const TYPE_SCALE: readonly Token[] = STEPS.map((px) =>
  tk(`text-${px}`, `${px}px`, `Type step ${px}`, USES[px], "Sizes between steps", "system"),
);

export const TYPE_ROLES: readonly TypeRole[] = [
  { name: "footer-word", family: "display", weight: 600, size: "clamp(84px, 19vw, 300px)", leading: "1",
    tracking: "-0.055em", role: "Footer wordmark", useFor: "The giant 6labs at the page's foot",
    neverFor: "Any other line", source: `${W}CopyLine.tsx:67`,
    classes: "font-display text-[clamp(84px,19vw,300px)] font-semibold tracking-[-0.055em]" },
  { name: "hero-full", family: "display", weight: 500, size: "34px", leading: "1.05", tracking: "-0.025em",
    steps: [{ at: "min-561", size: "36px" }, { at: "min-901", size: "42px" }, { at: "xl", size: "54px" },
      { at: "min-1600", size: "64px" }, { at: "min-1920", size: "76px" }, { at: "min-2560", size: "88px" },
      { at: "short", size: "48px" }],
    role: "Hero headline, full view", useFor: "The one h1 of the full-view hero",
    neverFor: "Section headings", source: `${W}Hero.tsx:18`, classes: "font-display font-medium tracking-tight leading-[1.05] FULL_TITLE" },
  { name: "closing", family: "display", weight: 500, size: "clamp(38px, 5.2vw, 74px)", leading: "1.05",
    tracking: "-0.045em", role: "Closing headline", useFor: "The closing line before the footer",
    neverFor: "Section heads", source: `${W}Closing.tsx:22`,
    classes: "font-display text-[clamp(38px,5.2vw,74px)] font-medium leading-[1.05] tracking-[-0.045em]" },
  { name: "hero", family: "display", weight: 500, size: "34px", leading: "1.05", tracking: "-0.025em",
    steps: [{ at: "md", size: "56px" }], role: "Hero and player headline",
    useFor: "The container hero h1 and the player title", neverFor: "Section heads", source: `${W}Hero.tsx:187`,
    classes: "font-display font-medium tracking-tight leading-[1.05] text-[34px] md:text-[56px]" },
  { name: "h2", family: "display", weight: 500, size: "30px", leading: "1.1", tracking: "-0.025em",
    steps: [{ at: "md", size: "44px" }], role: "Section heading", useFor: "Jobs and FAQ heads, new section heads",
    neverFor: "Card titles", source: `${W}Jobs.tsx:106`,
    classes: "font-display text-[30px] md:text-[44px] font-medium leading-[1.1] tracking-tight" },
  { name: "scroll-line", family: "display", weight: 500, size: "26px", leading: "1.3", tracking: "-0.025em",
    steps: [{ at: "md", size: "44px" }], role: "Scroll line statement", useFor: "The centred statement that fills on scroll",
    neverFor: "Headings", source: `${W}ScrubLine.tsx:120`,
    classes: "font-display text-[26px] md:text-[44px] font-medium leading-[1.3] tracking-tight" },
  { name: "carousel-title", family: "display", weight: 500, size: "28px", leading: "1.1", tracking: "-0.025em",
    steps: [{ at: "md", size: "36px" }], role: "Carousel player title", useFor: "The player name under lg",
    neverFor: "Light grounds", source: `${W}PlayerCarousel.tsx:84`,
    classes: "font-display text-[28px] font-medium leading-[1.1] tracking-tight md:text-[36px]" },
  { name: "stat", family: "display", weight: 500, size: "30px", leading: "1", tracking: "-0.025em", tabular: true,
    role: "Stat number", useFor: "Hero numbers", neverFor: "Prose numbers", source: `${W}HeroBits.tsx:55`,
    classes: "font-display text-[30px] font-medium leading-none tracking-tight tabular-nums" },
  { name: "comparison-name", family: "display", weight: 500, size: "26px", leading: "1.1", tracking: "-0.025em",
    steps: [{ at: "md", size: "34px" }], role: "Comparison name",
    useFor: "The maker's name heading each comparison card, 500 on the grey and 400 (6labs) on the navy",
    neverFor: "Section heads", source: `${W}Understands.tsx:31`,
    classes: "font-display text-[26px] md:text-[34px] leading-[1.1] tracking-tight" },
  { name: "vs", family: "display", weight: 400, size: "27px", leading: "1", tracking: "-0.025em",
    steps: [{ at: "md", size: "34px" }], role: "The vs word",
    useFor: "The vs on the disc between the comparison cards, decorative and aria-hidden",
    neverFor: "Text a reader must read", source: `${W}Understands.tsx:87`,
    classes: "font-display text-[34px] font-normal tracking-tight max-md:text-[27px] leading-none" },
  { name: "card-name", family: "display", weight: 500, size: "22px", leading: "1.25", tracking: "-0.025em",
    role: "Card name", useFor: "Player cards", neverFor: "Section heads",
    source: `${W}Players.tsx:230`, classes: "font-display text-[22px] font-medium leading-tight tracking-tight" },
  { name: "wordmark", family: "display", weight: 500, size: "24px", leading: "32px", tracking: "-0.025em",
    role: "Logo wordmark", useFor: "The 6labs lockup in the header and footer", neverFor: "Headings",
    source: `${W}Header.tsx:73`, classes: "font-display text-2xl font-medium tracking-tight" },
  { name: "card-title", family: "display", weight: 500, size: "20px", leading: "1.25", tracking: "-0.03em",
    role: "Card title", useFor: "Job cards and new card titles", neverFor: "Body", source: `${W}Jobs.tsx:164`,
    classes: "font-display text-[20px] font-medium leading-tight tracking-[-0.03em]" },
  { name: "menu-row", family: "display", weight: 400, size: "20px", leading: "1.5", tracking: "-0.025em",
    role: "Mobile menu row", useFor: "Rows of the mobile menu", neverFor: "Desktop nav", source: `${W}MobileMenu.tsx:91`,
    classes: "font-display text-[20px] font-normal tracking-tight" },
  { name: "question", family: "display", weight: 500, size: "16px", leading: "1.375", tracking: "-0.02em",
    steps: [{ at: "md", size: "18px" }], role: "FAQ question", useFor: "Accordion triggers", neverFor: "Body",
    source: `${W}Faq.tsx:45`, classes: "font-display text-[16px] md:text-[18px] font-medium leading-snug tracking-[-0.02em]" },
  { name: "lede-full", family: "sans", weight: 400, size: "16px", leading: "1.55", tracking: "-0.015em",
    steps: [{ at: "min-561", size: "16.5px" }, { at: "min-901", size: "15px" }, { at: "xl", size: "16px" },
      { at: "min-1600", size: "18px" }, { at: "min-1920", size: "20px" }, { at: "min-2560", size: "22px" }],
    role: "Lede, full view", useFor: "The full-view hero's lede", neverFor: "Body copy", source: `${W}Hero.tsx:20`,
    classes: "FULL_LEDE" },
  { name: "lede", family: "sans", weight: 400, size: "14px", leading: "1.625", tracking: "0",
    steps: [{ at: "md", size: "15px" }], role: "Lede, container hero", useFor: "The line under the container h1",
    neverFor: "Long body", source: `${W}Hero.tsx:205`, classes: "text-[14px] md:text-[15px] leading-relaxed" },
  { name: "player-body", family: "sans", weight: 400, size: "16px", leading: "1.625", tracking: "0",
    steps: [{ at: "md", size: "18px" }], role: "Player body", useFor: "The player description on blue",
    neverFor: "Light grounds", source: `${W}Players.tsx:127`, classes: "font-sans text-[16px] md:text-[18px] leading-relaxed" },
  { name: "comparison", family: "sans", weight: 400, size: "16px", leading: "1.5", tracking: "0",
    steps: [{ at: "md", size: "18px" }], role: "Comparison line",
    useFor: "The two lines inside each comparison card, in the card's one ink", neverFor: "Headings",
    source: `${W}Understands.tsx:32`, classes: "font-sans text-[16px] md:text-[18px] font-normal leading-[1.5]" },
  { name: "body-l", family: "sans", weight: 400, size: "15px", leading: "1.5", tracking: "0",
    steps: [{ at: "md", size: "16px" }], role: "Body L", useFor: "The closing line",
    neverFor: "Labels", source: `${W}Closing.tsx:27`, classes: "font-sans text-[15px] leading-[1.5] md:text-[16px]" },
  { name: "subline", family: "sans", weight: 400, size: "15px", leading: "1.375", tracking: "0",
    steps: [{ at: "md", size: "16px" }], role: "Section subline", useFor: "Section sublines, the carousel body on blue",
    neverFor: "Long reading", source: `${W}Jobs.tsx:109`, classes: "font-sans text-[15px] md:text-[16px] leading-snug" },
  { name: "answer", family: "sans", weight: 400, size: "14px", leading: "1.6", tracking: "0",
    steps: [{ at: "md", size: "15px" }], role: "FAQ answer", useFor: "Accordion answers", neverFor: "Labels",
    source: `${W}Faq.tsx:68`, classes: "font-sans text-[15px] leading-[1.6] max-md:text-[14px]" },
  { name: "stat-label", family: "sans", weight: 400, size: "14px", leading: "1.375", tracking: "0",
    steps: [{ at: "md", size: "15px" }], role: "Stat label", useFor: "The words under the hero numbers",
    neverFor: "Body", source: `${W}HeroBits.tsx:46`, classes: "font-sans text-[14px] md:text-[15px] leading-snug" },
  { name: "nav", family: "sans", weight: 400, size: "15px", leading: "1.5", tracking: "-0.01em",
    role: "Nav link", useFor: "Header links, menu rows", neverFor: "Body", source: `${W}Header.tsx:86`,
    classes: "text-[15px] font-normal tracking-[-0.01em]" },
  { name: "cta", family: "sans", weight: 500, size: "15px", leading: "1.5", tracking: "0",
    role: "Primary CTA label", useFor: "Try now only. System buttons take button-label",
    neverFor: "Body", source: `${W}PrimaryCta.tsx:100`, classes: "text-[15px] font-medium" },
  { name: "button-label", family: "sans", weight: 500, size: "14px", leading: "1.5", tracking: "-0.01em",
    role: "Button label",
    useFor: "System Button labels: 12 / 13 / 14 / 15 / 15 at xs to xl (14 is md), all at -0.01em",
    neverFor: "Try now, which keeps cta", source: `${DS}button-styles.ts:25`,
    classes: "font-sans text-[14px] font-medium tracking-[-0.01em]" },
  { name: "dialog-title", family: "display", weight: 500, size: "24px", leading: "30px", tracking: "-0.03em",
    role: "Dialog title", useFor: "The title of a Dialog or sheet", neverFor: "Section heads",
    source: `${DS}dialog-styles.ts:33`, classes: "font-display text-[24px] font-medium leading-[30px] tracking-[-0.03em]" },
  { name: "dialog-description", family: "sans", weight: 400, size: "15px", leading: "22px", tracking: "0",
    role: "Dialog description", useFor: "The line under a dialog title", neverFor: "The body, which takes dialog-body",
    source: `${DS}dialog-styles.ts:35`, classes: "text-[15px] leading-[22px]" },
  { name: "dialog-body", family: "sans", weight: 400, size: "15px", leading: "1.6", tracking: "0",
    role: "Dialog body", useFor: "The scrolling body of a Dialog", neverFor: "Labels",
    source: `${DS}dialog-styles.ts:37`, classes: "text-[15px] leading-[1.6]" },
  { name: "field-label", family: "sans", weight: 500, size: "13px", leading: "18px", tracking: "-0.01em",
    role: "Field label", useFor: "The label over a field, a Select, a SearchField and a Slider, and a choice group's legend",
    neverFor: "Body", source: `${DS}field-styles.ts:83`,
    classes: "font-sans text-[13px] font-medium leading-[18px] tracking-[-0.01em]" },
  { name: "helper", family: "sans", weight: 400, size: "13px", leading: "18px", tracking: "0",
    role: "Helper line", useFor: "Field helper and error lines, choice descriptions, the toast body, the Slider value",
    neverFor: "Labels", source: `${DS}Field.tsx:107`, classes: "font-sans text-[13px] leading-[18px]" },
  { name: "counter", family: "sans", weight: 400, size: "12px", leading: "18px", tracking: "0", tabular: true,
    role: "Character count", useFor: "The count under a field with a maxLength", neverFor: "Prose numbers",
    source: `${DS}Field.tsx:115`, classes: "font-sans text-[12px] leading-[18px] tabular-nums" },
  { name: "choice-label", family: "sans", weight: 400, size: "14px", leading: "20px", tracking: "0",
    role: "Choice label", useFor: "Checkbox, Radio and Switch labels", neverFor: "Field labels, which take field-label",
    source: `${DS}choice-styles.ts:17`, classes: "text-[14px] leading-5" },
  { name: "list-row", family: "sans", weight: 400, size: "15px", leading: "22px", tracking: "0",
    role: "List row", useFor: "Select and SearchField option rows and their empty line", neverFor: "Body",
    source: `${DS}select-panel.tsx:134`, classes: "font-sans text-[15px] leading-[22px]" },
  { name: "toast-title", family: "sans", weight: 500, size: "14px", leading: "20px", tracking: "0",
    role: "Toast title", useFor: "The first line of a toast", neverFor: "Body", source: `${DS}Toast.tsx:84`,
    classes: "text-[14px] font-medium leading-5" },
  { name: "tooltip", family: "sans", weight: 500, size: "12px", leading: "16px", tracking: "0",
    role: "Tooltip words", useFor: "The words in a tooltip bubble", neverFor: "Body", source: `${DS}TooltipBubble.tsx:28`,
    classes: "font-sans text-[12px] font-medium leading-4" },
  { name: "group-caps", family: "sans", weight: 500, size: "11px", leading: "16px", tracking: "0.14em", caps: true,
    role: "Group caps", useFor: "The group names inside a Select or SearchField list", neverFor: "Sentences",
    source: `${DS}select-panel.tsx:187`, classes: "font-sans text-[11px] font-medium uppercase leading-4 tracking-[0.14em]" },
  { name: "body-s", family: "sans", weight: 400, size: "14px", leading: "1.4", tracking: "-0.01em",
    role: "Body S", useFor: "Job body and card body", neverFor: "Long reading",
    source: `${W}Jobs.tsx:167`, classes: "font-sans text-[14px] leading-[1.4] tracking-[-0.01em]" },
  { name: "card-tagline", family: "sans", weight: 400, size: "14px", leading: "1.375", tracking: "0",
    role: "Card tagline", useFor: "The tagline under a player card's name, hidden under lg", neverFor: "Body",
    source: `${W}Players.tsx:238`, classes: "font-sans text-[14px] leading-snug" },
  { name: "trait-label", family: "sans", weight: 400, size: "14px", leading: "1.5", tracking: "0",
    role: "Trait label", useFor: "The trait bar labels on blue, 13px in the dense card", neverFor: "Light grounds",
    source: `${W}PlayerTraits.tsx:37`, classes: "font-sans text-[14px]" },
  { name: "caption-l", family: "sans", weight: 400, size: "13.5px", leading: "1.5", tracking: "-0.01em",
    role: "Caption 13.5", useFor: "The closing small line, footer links", neverFor: "New work, which takes 13 or 14",
    source: `${W}Closing.tsx:34`, classes: "font-sans text-[13.5px] tracking-[-0.01em]" },
  { name: "caption", family: "sans", weight: 400, size: "13px", leading: "1.625", tracking: "0",
    role: "Caption 13", useFor: "The social proof line", neverFor: "Body", source: `${W}Hero.tsx:236`,
    classes: "font-sans text-[13px] leading-relaxed" },
  { name: "tab-label", family: "sans", weight: 500, size: "13px", leading: "1.5", tracking: "0",
    role: "Tab label", useFor: "The jobs switch's tabs", neverFor: "Body", source: `${W}Jobs.tsx:128`,
    classes: "font-sans text-[13px] font-medium" },
  { name: "footer-base", family: "sans", weight: 400, size: "13px", leading: "1.5", tracking: "-0.01em",
    role: "Footer base", useFor: "The footer's own text, which its links and legal line inherit", neverFor: "Body",
    source: `${W}Footer.tsx:26`, classes: "font-sans text-[13px] tracking-[-0.01em]" },
  { name: "footer-intro", family: "sans", weight: 400, size: "14px", leading: "1.65", tracking: "-0.015em",
    role: "Footer intro", useFor: "The line under the footer lockup", neverFor: "Body", source: `${W}Footer.tsx:48`,
    classes: "text-[14px] leading-[1.65] tracking-[-0.015em]" },
  { name: "footer-head", family: "sans", weight: 600, size: "13.5px", leading: "1.5", tracking: "-0.02em",
    role: "Footer column head", useFor: "The footer's column titles", neverFor: "New work, which takes 13 or 14",
    source: `${W}Footer.tsx:57`, classes: "text-[13.5px] font-semibold tracking-[-0.02em]" },
  { name: "micro", family: "sans", weight: 400, size: "12px", leading: "1.5", tracking: "-0.01em",
    role: "Micro 12", useFor: "The footer copy line's model pills", neverFor: "Body",
    source: `${W}CopyLine.tsx:102`, classes: "text-[12px] tracking-[-0.01em]" },
  { name: "eyebrow", family: "sans", weight: 500, size: "11px", leading: "1.5", tracking: "0.18em", caps: true,
    role: "Eyebrow caps", useFor: "The scroll cue and the loader label", neverFor: "Sentences",
    source: `${W}ScrollCue.tsx:25`, classes: "text-[11px] font-medium uppercase tracking-[0.18em]" },
  { name: "code-tag", family: "sans", weight: 600, size: "11px", leading: "1.5", tracking: "0.025em",
    role: "Code tag", useFor: "Language codes in the menu", neverFor: "Labels", source: `${W}LanguageMenu.tsx:95`,
    classes: "text-[11px] font-semibold tracking-wide" },
  { name: "card-meta", family: "mono", weight: 400, size: "11px", leading: "1.5", tracking: "0.14em", caps: true,
    steps: [{ at: "max-lg", size: "10px", tracking: "0.08em" }],
    role: "Card meta", useFor: "Model number and status on player cards", neverFor: "Sentences, badge labels",
    source: `${W}Players.tsx:247`, classes: "font-mono text-[11px] uppercase tracking-[0.14em]" },
  { name: "badge", family: "mono", weight: 500, size: "11px", leading: "1", tracking: "0.12em", caps: true,
    role: "Badge label", useFor: "Badge labels: 0.12em at md, 0.08em at sm", neverFor: "Sentences",
    source: `${DS}Badge.tsx:21`,
    classes: "font-mono text-[11px] font-medium uppercase leading-none tracking-[0.12em]" },
  { name: "terminal", family: "mono", weight: 400, size: "12.5px", leading: "22px", tracking: "0",
    steps: [{ at: "max-md", size: "11.5px", leading: "20px" }], role: "Terminal text",
    useFor: "The jobs terminal", neverFor: "Light grounds", source: `${W}JobTerminal.tsx:142`,
    classes: "font-[family-name:var(--font-jbmono)] text-[12.5px] leading-[22px] max-md:text-[11.5px] max-md:leading-[20px]" },
];

/** Inline style for a type role, read from the --ds-type-* properties TokenStyle prints: family, size,
 *  leading, tracking and weight, and the role's case and figures, so a caps or tabular role keeps them. */
export function typeStyle(name: string): {
  fontFamily: string; fontSize: string; lineHeight: string; letterSpacing: string; fontWeight: string;
  textTransform: string; fontVariantNumeric: string;
} {
  const v = (k: string) => `var(--ds-type-${name}-${k})`;
  return { fontFamily: v("family"), fontSize: v("size"), lineHeight: v("leading"), letterSpacing: v("tracking"),
    fontWeight: v("weight"), textTransform: v("case"), fontVariantNumeric: v("numeric") };
}
