// Catalog entries for Signature effects and Shell, in page order. Effects run under sub-labels, as Components
// does: the page's stacking, the floor, the grounds and the scroll, the players, then the rules every effect
// keeps.
import { defineGroup, sectionFile as f, site, sys, tiles } from "./catalog-types";

export const EFFECTS = defineGroup({
  id: "effects",
  title: "Signature effects",
  lead: "The site's own effects, from the glass tile floor to the scroll line and the accent water, and the compositor rule that keeps them smooth.",
  sections: [
    { id: "layer-stack", title: "Layer stack", sub: "The page", file: f("effects/layer-stack"), designMd: "5.1", covers: [] },
    {
      id: "tile-floor",
      title: "The glass tile floor",
      sub: "The floor",
      file: f("effects/tile-floor"),
      designMd: "5.2",
      covers: [tiles("TileFloor")],
    },
    {
      id: "tile-states",
      title: "Tile states",
      sub: "The floor",
      file: f("effects/tile-states"),
      designMd: "5.3",
      covers: [tiles("TileFloor", { states: "default focused activated spent resetting" })],
    },
    { id: "tile-activation", title: "Activation sweep", sub: "The floor", file: f("effects/tile-activation"), designMd: "5.4", covers: [] },
    {
      id: "holograms",
      title: "Characters and holograms",
      sub: "The floor",
      file: f("effects/characters-holograms"),
      designMd: "5.5",
      covers: [],
    },
    {
      id: "floor-lifecycle",
      title: "Load-in, autoplay and loaders",
      sub: "The floor",
      file: f("effects/floor-lifecycle"),
      designMd: "5.6",
      covers: [site("HeroLoader"), site("FloorLogo", { file: "HeroBits" })],
    },
    {
      id: "ascii-field",
      title: "Glyph field",
      sub: "Grounds, scroll and water",
      file: f("effects/ascii-field"),
      designMd: "5.7",
      covers: [site("AsciiBackdrop", { variants: "page terminal" })],
    },
    {
      id: "scroll-line",
      title: "Scroll line, liquid and floating tiles",
      sub: "Grounds, scroll and water",
      file: f("effects/scroll-line"),
      designMd: "5.8",
      covers: [site("ScrubLine"), site("LiquidLine"), site("FloatingBadges")],
    },
    {
      id: "accent-water",
      title: "Accent water",
      sub: "Grounds, scroll and water",
      file: f("effects/accent-water"),
      designMd: "5.9",
      covers: [site("AccentWave")],
    },
    {
      id: "portrait-sweep",
      title: "Human / AI swap",
      sub: "Players",
      file: f("effects/portrait-sweep"),
      designMd: "5.10",
      covers: [site("PortraitSwap"), site("StackedSwap"), site("PlayerPortrait")],
    },
    {
      id: "doodles",
      title: "Doodles",
      sub: "Players",
      file: f("effects/doodles"),
      designMd: "5.11",
      covers: [site("PlayerDoodles"), site("DoodleStroke")],
    },
    {
      id: "families",
      title: "Halftone, chromatic split, grain",
      sub: "Rules",
      file: f("effects/families"),
      designMd: "5.12",
      covers: [],
    },
    {
      id: "perf-rule",
      title: "Compositor-safe rule",
      sub: "Rules",
      file: f("effects/perf-rule"),
      designMd: "5.13",
      covers: [site("PerfBoot")],
    },
  ],
});

export const SHELL = defineGroup({
  id: "shell",
  title: "Shell",
  lead: "The parts every page carries: the lockup, the header and its menus, the footer and the way back to the top.",
  sections: [
    {
      id: "identity",
      title: "Logo and identity",
      file: f("shell/identity"),
      designMd: "6.1",
      covers: [
        site("SixLabsMark", { file: "brand-marks" }),
        site("SixLabsLogo", { file: "brand-marks" }),
        site("ChatGptMark", { file: "brand-marks" }),
        sys("Lockup", { na: "hover pressed disabled" }),
      ],
    },
    {
      id: "header",
      title: "Header",
      file: f("shell/header"),
      designMd: "6.2",
      covers: [site("Header", { variants: "default clear phone", states: "rest scrolled onBlue held top" })],
    },
    {
      id: "mobile-menu",
      title: "Mobile menu",
      file: f("shell/mobile-menu"),
      designMd: "6.3",
      covers: [site("MobileMenu", { states: "closed open row-pressed" })],
    },
    {
      id: "language-menu",
      title: "Language menu",
      file: f("shell/language-menu"),
      designMd: "6.4",
      covers: [site("LanguageMenu", { states: "rest hover open row-active row-selected" })],
    },
    {
      id: "footer",
      title: "Footer and copy line",
      file: f("shell/footer"),
      designMd: "6.5",
      covers: [
        site("Footer", { variants: "phone tablet desktop" }),
        site("CopyLine"),
        site("Word", { file: "CopyLine" }),
        site("CopyLinePicture"),
      ],
    },
    {
      id: "back-to-top",
      title: "Back to top and scroll cue",
      file: f("shell/back-to-top"),
      designMd: "6.6",
      covers: [site("BackToTop", { states: "hidden shown hover" }), site("ScrollCue", { states: "present away" })],
    },
    {
      id: "behaviours",
      title: "Shell behaviours",
      file: f("shell/behaviours"),
      designMd: "6.7",
      covers: [site("ClickLock"), site("SafariScroll")],
    },
  ],
});
